/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package poolup;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class owner extends javax.swing.JFrame {
String usero;
int id;
    /** Creates new form owner */
    public owner() {
        
        initComponents();
    }
public void setUsername(String s)
{
    int id=1;
usero=s;
System.out.println(usero);
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        route = new javax.swing.JComboBox<>();
        gettrav = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        test = new javax.swing.JTable();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rat = new javax.swing.JTextField();
        rat1 = new javax.swing.JTextField();
        rat2 = new javax.swing.JTextField();
        rat3 = new javax.swing.JTextField();
        rat4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        route.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Route", "Ambattur", "K.K.Nagar", "Porur", "Vandalur", "Triplicane" }));
        getContentPane().add(route, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 26, -1, -1));

        gettrav.setText("Get travellers");
        gettrav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gettravActionPerformed(evt);
            }
        });
        getContentPane().add(gettrav, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 57, -1, -1));

        test.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Rating"
            }
        ));
        jScrollPane1.setViewportView(test);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, 359, 76));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, -1));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, -1));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 90, -1));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 90, -1));

        jButton2.setText("Confirm ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 314, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Travellers :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jButton1.setText("My Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rating");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));
        getContentPane().add(rat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 60, -1));
        getContentPane().add(rat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 60, -1));

        rat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rat2ActionPerformed(evt);
            }
        });
        getContentPane().add(rat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 60, -1));

        rat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rat3ActionPerformed(evt);
            }
        });
        getContentPane().add(rat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 60, -1));
        getContentPane().add(rat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 60, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\car3.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gettravActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gettravActionPerformed
        // TODO add your handling code here:
        System.out.println("-------- PostgreSQL "
				+ "JDBC Connection Testing ------------");

		try {

			Class.forName("org.postgresql.Driver");

		} catch (ClassNotFoundException e) {

			System.out.println("Where is your PostgreSQL JDBC Driver? "
					+ "Include in your library path!");
			e.printStackTrace();
			return;

		}

		System.out.println("PostgreSQL JDBC Driver Registered!");

		Connection connection = null;

		try {
                    String op="'";
String r=op+route.getSelectedItem()+op;

			connection = DriverManager.getConnection(
					"jdbc:postgresql://localhost:5432/postgres", "postgres",
					"sowmya");
                        Statement stmt = null;
                        stmt = connection.createStatement();
                        String sql="select * from gettraveler("+r+")";
                        
                        ResultSet rs=stmt.executeQuery(sql);
                        int i=0;
                        while(rs.next())
                        {test.setValueAt(rs.getString(1),i,0);
                        test.setValueAt(rs.getString(2),i,1);
                        i++;}
                        
                     
         /*stmt.close();*/


		} catch (SQLException e) {

			System.out.println("Connection Failed! Check output console");
                        
			e.printStackTrace();
			return;

		}

		if (connection != null) {
			System.out.println("You made it, take control your database now!");
		} else {
			System.out.println("Failed to make connection!");
		}
    }//GEN-LAST:event_gettravActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println("-------- PostgreSQL "
				+ "JDBC Connection Testing ------------");

		try {

			Class.forName("org.postgresql.Driver");

		} catch (ClassNotFoundException e) {

			System.out.println("Where is your PostgreSQL JDBC Driver? "
					+ "Include in your library path!");
			e.printStackTrace();
			return;

		}

		System.out.println("PostgreSQL JDBC Driver Registered!");

		Connection connection = null;

		try {
                    String op="'";
String tr1,tr2,tr3,tr4,sql,sql1,sql2,sql3,sql4;int ta1=0,ta2=0,ta3=0,ta4=0;
int ra1=0,ra2=0,ra3=0,ra4=0;
                    if(t1.getText().equals(""))
                    ta1++;
if(t2.getText().equals(""))
{
ta2++;}
if(t3.getText().equals(""))
{ta3++;}
if(t4.getText().equals(""))
{ta4++;}
usero=op+usero+op;
 tr1=op+t1.getText()+op;
tr2=op+t2.getText()+op;
tr3=op+t3.getText()+op;
tr4=op+t4.getText()+op;
Date d=new Date();
String dates=d.toString();
dates=op+dates+op;
int rating1=0;
int rating2=0;
int rating3=0;
int rating4=0;
if(rat.getText().equals(""))
{ ra1++;}
else
    rating1=Integer.parseInt(rat.getText());
if(rat2.getText().equals(""))
{
   
ra2++;}
else
    rating2=Integer.parseInt(rat2.getText()); 
if(rat3.getText().equals(""))
{ra3++;}
else
    rating3=Integer.parseInt(rat3.getText());
if(rat4.getText().equals(""))
{ra4++;}
else
    rating4=Integer.parseInt(rat4.getText());

int rides;
			connection = DriverManager.getConnection(
					"jdbc:postgresql://localhost:5432/postgres", "postgres",
					"sowmya");
                        Statement stmt = null;
                                Statement stmt4 = null;
                                Statement stmt5 = null;
                                Statement stmt6 = null;
                                Statement stmt7 = null;
                                Statement stmt8 = null;
                                Statement stmt9 = null;
                        stmt = connection.createStatement();
                        stmt4 = connection.createStatement();
                        stmt5 = connection.createStatement();
                        stmt6 = connection.createStatement();
                        stmt7 = connection.createStatement();
                        stmt8 = connection.createStatement();
                        stmt9 = connection.createStatement();
                        if(ta1==0)
                        {sql="insert into rides (owner,traveller,date_of_ride)values("+usero+","+tr1+","+dates+")";
                        stmt.executeUpdate(sql);}
                        if(ta2==0)
                        {sql2="insert into rides (owner,traveller,date_of_ride)values("+usero+","+tr2+","+dates+")";
                        stmt.executeUpdate(sql2);}
                        if(ta3==0)
                        {sql3="insert into rides (owner,traveller,date_of_ride)values("+usero+","+tr3+","+dates+")";
                        stmt.executeUpdate(sql3);}
                        if(ta4==0)
                        {sql4="insert into rides (owner,traveller,date_of_ride)values("+usero+","+tr4+","+dates+")";
                        stmt.executeUpdate(sql4);}
                        
                        
                        stmt4.executeUpdate("update owner set rides=rides+1 where username="+usero);
                        
                        ResultSet r2=stmt5.executeQuery("select * from owner where username="+usero);
                        r2.next();
                        rides=Integer.parseInt(r2.getString(7));
                        if(rides>5)
                            JOptionPane.showMessageDialog(null,"Congratulations!!!You have got a discount!!!");
                        
                   JOptionPane.showMessageDialog(null, "Booking Confirmed");
                        id++;
                        if(ra1==0)
                            stmt6.executeQuery("select travrating("+rating1+","+tr1+")");
                        if(ra2==0)
                            stmt7.executeQuery("select travrating("+rating2+","+tr2+")");
                        if(ra3==0)
                            stmt8.executeQuery("select travrating("+rating3+","+tr3+")");
                        if(ra4==0)
                            stmt9.executeQuery("select travrating("+rating4+","+tr4+")");  
                            
                        
                        
                        
                        
                     
         stmt.close();
         JOptionPane.showMessageDialog(null,"Booking confirmed");


		} catch (SQLException e) {

			System.out.println("Connection Failed! Check output console");
                        
			e.printStackTrace();
			return;

		}

		if (connection != null) {
			System.out.println("You made it, take control your database now!");
		} else {
			System.out.println("Failed to make connection!");
		}
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ProfileOwner owner=new ProfileOwner();
                        owner.setVisible(true);
                        owner.setusername(usero);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rat2ActionPerformed

    private void rat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rat3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rat3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gettrav;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField rat;
    private javax.swing.JTextField rat1;
    private javax.swing.JTextField rat2;
    private javax.swing.JTextField rat3;
    private javax.swing.JTextField rat4;
    private javax.swing.JComboBox<String> route;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTable test;
    // End of variables declaration//GEN-END:variables

}
